In [1]:
from dyno import dynare

In [5]:
report = dynare("tutorials/session_2/rbc_fixed.mod")

In [6]:
report.d

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.94190599, 0.95      , 1.07784475,        inf,
              inf,        inf,        inf,        inf,        inf,
              inf])

In [7]:
report.moments

array([[ 7.34994996e-04, -3.97804289e-06,  1.99567669e-03,
         4.20043588e-05,  9.91114604e-03,  3.66380874e-04,
         1.10137587e-03,  6.75183687e-04],
       [-3.97804289e-06,  1.58833385e-06,  4.16814376e-06,
         5.08193552e-06, -1.42438499e-04,  2.03594471e-05,
         1.63814042e-05,  1.45076835e-05],
       [ 1.99567669e-03,  4.16814376e-06,  5.56173064e-03,
         1.64776746e-04,  2.60626226e-02,  1.20826864e-03,
         3.20394533e-03,  2.00679751e-03],
       [ 4.20043588e-05,  5.08193552e-06,  1.64776746e-04,
         2.03915578e-05,  2.65519257e-04,  9.66480158e-05,
         1.38652375e-04,  1.00130058e-04],
       [ 9.91114604e-03, -1.42438499e-04,  2.60626226e-02,
         2.65519257e-04,  1.38680646e-01,  3.67429549e-03,
         1.35854415e-02,  8.07530987e-03],
       [ 3.66380874e-04,  2.03594471e-05,  1.20826864e-03,
         9.66480158e-05,  3.67429549e-03,  5.01234087e-04,
         8.67614961e-04,  5.95554103e-04],
       [ 1.10137587e-03,  1.63814042e-05,  3.20394533e-03,
         1.38652375e-04,  1.35854415e-02,  8.67614961e-04,
         1.96899083e-03,  1.27073779e-03],
       [ 6.75183687e-04,  1.45076835e-05,  2.00679751e-03,
         1.00130058e-04,  8.07530987e-03,  5.95554103e-04,
         1.27073779e-03,  8.30769231e-04]])

In [17]:
report?

Type:        RunResults
String form: RunResults(model='rbc_fixed', solution=<computed>, simulation=<computed>, elapsed=0.030s)
File:        ~/Teaching/ensae/ae2e6/.pixi/envs/default/lib/python3.12/site-packages/dyno/report.py
Docstring:
Unified result container returned by model ``run()`` methods and ``dsge_report``.

All fields are optional and populated progressively during the pipeline.
Display methods adapt to whatever data is available.

In [16]:
report.moments.shape

(8, 8)

In [14]:
cond, uncond = report.moments
print("Moments conditionnels :")
print(cond)
print("Moments inconditionnels :")
print(uncond)

ValueError: too many values to unpack (expected 2)

In [9]:
report.simulation

{'epsilon':             c         r         w         n         k         i         y  \
 0    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 1    0.002960  0.000526  0.013213  0.002005  0.009202  0.009202  0.012162
 2    0.003294  0.000459  0.013497  0.001803  0.017410  0.008438  0.011732
 3    0.003583  0.000397  0.013711  0.001617  0.024703  0.007729  0.011312
 4    0.003832  0.000341  0.013863  0.001446  0.031158  0.007072  0.010904
 ..        ...       ...       ...       ...       ...       ...       ...
 96   0.000276 -0.000017  0.000598 -0.000038  0.004630 -0.000090  0.000186
 97   0.000264 -0.000017  0.000571 -0.000037  0.004427 -0.000086  0.000178
 98   0.000252 -0.000016  0.000546 -0.000035  0.004234 -0.000083  0.000169
 99   0.000241 -0.000015  0.000521 -0.000034  0.004048 -0.000080  0.000162
 100  0.000231 -0.000015  0.000498 -0.000032  0.003870 -0.000077  0.000154

             a
 0    0.000000
 1    0.009000
 2    0.008550
 3    0.008122
 4    0.007716
 ..        ...
 96   0.000069
 97   0.000065
 98   0.000062
 99   0.000059
 100  0.000056

 [101 rows x 8 columns]}

In [13]:
dr = report.solution.decision_rule
print("X")
print(dr.X)
print("Y")
print(dr.X)
print("Σ")
print(dr.Σ)

X
[[ 0.          0.          0.          0.          0.05239829  0.
   0.          0.31241831]
 [ 0.          0.          0.          0.         -0.00443606  0.
   0.          0.05550534]
 [ 0.          0.          0.          0.          0.10260005  0.
   0.          1.39474574]
 [ 0.          0.          0.          0.         -0.01107652  0.
   0.          0.21166995]
 [ 0.          0.          0.          0.          0.94190599  0.
   0.          0.97134612]
 [ 0.          0.          0.          0.         -0.03309401  0.
   0.          0.97134612]
 [ 0.          0.          0.          0.          0.01930427  0.
   0.          1.28376443]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.95      ]]
Y
[[ 0.          0.          0.          0.          0.05239829  0.
   0.          0.31241831]
 [ 0.          0.          0.          0.         -0.00443606  0.
   0.          0.05550534]
 [ 0.          0.          0.          0.          0.10260005  0.
   0.          1.39474574]
 [ 0.          0.          0.          0.         -0.01107652  0.
   0.          0.21166995]
 [ 0.          0.          0.          0.          0.94190599  0.
   0.          0.97134612]
 [ 0.          0.          0.          0.         -0.03309401  0.
   0.          0.97134612]
 [ 0.          0.          0.          0.          0.01930427  0.
   0.          1.28376443]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.95      ]]
Σ
[[8.1e-05]]

In [10]:
model = dyno.DynoModel("rbc.dyno")

In [12]:
model.solve()